# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "auto-update RFCs"

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 22 * * *"

jobs:
  auto-rfcs:
    name: "Auto-update PHP RFCs"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          coverage: "none"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@v1"

      - name: "Install pandoc"
        run: |
          curl -LSs -o pandoc.deb https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb
          sudo apt install -y ./pandoc.deb
          rm pandoc.deb

      - name: "Automatically update PHP RFCs"
        run: "./bin/auto_rfcs.sh"
        env:
          INPUT_GITHUB_TOKEN: ${{ secrets.TOKEN }}
