# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "auto pull request"

on:
  push:
    branches:
      - "auto-rfcs/**"

jobs:
  pull-request:
    name: "Auto pull request"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Open pull requests for auto-rfcs/** branches"
        uses: "vsoch/pull-request-action@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BRANCH_PREFIX: "auto-rfcs/"
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_TITLE: "Update RFCs [Automated]"
          PULL_REQUEST_BODY: >
            This is an automated pull request to apply PHP wiki updates
            to the RFCs in this repository, including any new RFCs found
            on the wiki.
          PULL_REQUEST_UPDATE: true
